Fix typo in error message

diff --git a/bib2docx b/bib2docx
--- a/bib2docx
+++ b/bib2docx
@@ -72,7 +72,7 @@ done
 
 
 if [ "$bibfiles" = "" ]; then
-    echo "No biblioraphy specified. Aborting!" >&2
+    echo "No bibliography specified. Aborting!" >&2
     exit 1
 fi
 if [ "$output" = "" ]; then
